### ISSUE TITLE
[Feature request] Add support to query string in URL

### ISSUE THREAD

**Issue by jenkin** [yotkadata/meteo_hist#1]
## Actual behavior

If you set up parameters and create a chart, URL doesn't change and sharing a specific location is not possible.

## Expected behavior

On create, URL query string updates with all chosen parameters values. If page is loaded with a valid query string, parameters are initialized with chosen values.

## Bonus

Add a "share this" button and/or an embed code for current location.

**Comment by yotkadata** [comment]
Thanks @jenkin, it's definitely a good idea! The current setting using a rather simple Streamlit app doesn't allow this feature. But when I have time, I'll look into [st.experimental_get_query_params](https://docs.streamlit.io/library/api-reference/utilities/st.experimental_get_query_params). It should be possible with it.

**Comment by yotkadata** [comment]
I just added that feature:
https://github.com/yotkadata/meteo_hist/commit/922f6e7c7785d38d1c6d71227a594e79e3e62d11

When you create a graph, you'll find a share link below.

**Comment by jenkin** [comment]
Awesome, thanks!
