### ISSUE TITLE
[Feature Request] Add last date / updated

### ISSUE THREAD

**Issue by fewekoe** [yotkadata/meteo_hist#2]
Hi Jan,

amazing tool!

Could you embed a field showing the timestamp of the last date used/queried?

Best
F

**Comment by yotkadata** [comment]
Thanks @fewekoe! Sounds like a good idea. The data on open-meteo.com is usually delayed by some days, so displaying the date of the last data point sounds good to me. That's what you meant, correct? I'll work on it as soon as I can.

**Comment by fewekoe** [comment]
+1 that what's I meant! Thanks a ton

**Comment by yotkadata** [comment]
I added the last date used next to lat/lon in the lower left corner if the current year is displayed. Feel free to comment on it..
